env:
  GO_VERSION: "1.18.0"

steps:
  - label: ":docker: Build with Golang 1.18.0"
    command: |
      go build -o output_binary /workdir/hello/hello.go
      chmod +x output_binary
      buildkite-agent artifact upload "output_binary"
    plugins:
      - docker#v3.9.0:
          image: golang:1.18.0

  - label: ":stop: Please enter user name"
    type: block
    prompt: "User name / approval needed"
    fields:
      - text: "User Name"
        key: "release-name"
        hint: "Please enter your name"
      - select: "Go Ahead?"
        key: "release-type"
        default: "beta"
        options:
          - label: "Okay"
            value: "okay"
    command: |
      if [ -z "$BUILDKITE_RELEASE_NAME" ]; then
        echo "Error: No release-name provided."
        exit 1
      fi
      # Save the input metadata for use in later steps
      buildkite-agent meta-data set release-name "$BUILDKITE_RELEASE_NAME"

  - label: ":rocket: Deploy"
    command: |
      export USER_NAME=$(buildkite-agent meta-data get release-name)

      if [ -z "$USER_NAME" ]; then
        echo "Error: release-name metadata is empty!"
        exit 1
      fi

      echo "Deploying for user: $USER_NAME"
      
      # Download and deploy the binary
      buildkite-agent artifact download "output_binary" .
      chmod +x output_binary
      ./output_binary "$USER_NAME"
    plugins:
      - docker#v3.9.0:
          image: golang:1.18.0


