env:
  GO_VERSION: "1.18.0"

steps:
  # Step 1: Build and upload the Golang project artifact
  - label: ":docker: Build with Golang 1.18.0"
    command: |
      go build -o hello/hello /workdir/hello/hello.go
      chmod +x hello/hello
      buildkite-agent artifact upload "hello/hello"
    plugins:
      - docker#v3.9.0:
          image: golang:1.18.0

  # Step 2: Block step for user input (enter username)
  - label: ":stop: Please enter user name"
    type: block
    prompt: "User name / approval needed"
    fields:
      - text: "User Name"
        key: "username"
        hint: "Please enter your name"

  # Step 3: Download the artifact and run the compiled program
  - label: ":rocket: Deploy"
    command: |
      buildkite-agent artifact download "hello/hello" .
      chmod +x hello/hello
      ./hello/hello "$(buildkite-agent meta-data get username)"
    plugins:
      - docker#v3.9.0:
          image: golang:1.18.0

